require("plugins.plugins-setup")

require("core.options")
require("core.keymaps")

-- 插件
require("plugins/lualine")
require("plugins/nvim-tree")
require("plugins/treesitter")
require("plugins/lsp")
require("plugins/cmp")
require("plugins/comment")
require("plugins/autopairs")
require("plugins/bufferline")
require("plugins/gitsigns")
require("plugins/toggleterm")
require("plugins/format")
require("plugins/notify")
require("plugins/autosave")
require("plugins/blankline")
require("plugins/trouble")
require("plugins/telescope")
